--- 
- 
  hosts: localhost
  name: "Create and PUsh the docker image to docker hub"
  tasks: 
    - 
      command: "docker build .  webserverimagecicd"
      name: "Create docker image"
    - 
      command: "docker tag  webserverimagecicd arshabbir/webserverimagecicd"
      name: "Tag docker image"
    - 
      command: "docker push  arshabbir/webserverimagecicd"
      name: "Push the docker image to docker hub"
