--- 
- 
  hosts: localhost
  name: "Create and PUsh the docker image to docker hub"
  tasks: 
    - 
      command: "docker bukld .  webserverimage1"
      name: "Create docker image"
    - 
      command: "docker tag  webserverimage arshabbir/webserverimage"
      name: "Tag docker image"
    - 
      command: "docker push  arshabbir/webserverimage"
      name: "Push the docker image to docker hub"
