apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: appDeployment
  name: appdeployment
spec:
  replicas: 2
  strategy:
   type: RollingUpdate
   rollingUpdate:
    maxSurge: 1
    maxUnavailable: 25%
  selector:
   matchLabels:
      name: app-pod
  template:
    metadata:
      labels:
        name: app-pod
      name: app-pod
    spec:
      containers:
        -
          image: arshabbir/webserverimagecicd
          imagePullPolicy: Always
          name: webservercice
          ports:
            - containerPort: 8087
