apiVersion: v1
kind: Service
metadata:
 name: testservice
 labels:
  name: testservice
spec:
 selector:
   name: app-pod
 type: NodePort
 ports:
  - port: 8087
    targetPort: 8087
    nodePort: 31200

